language: node_js
os:
  - linux
  - osx
node_js:
  - node
  - "12"
script:
  - yarn run lint
  - yarn run build

deploy:
  provider: gcs
  access_key_id: GOOGFI4UVD2EJYIBQDQ4MQKJ
  secret_access_key:
    secure: hLIrpU10THCTb3PgbwWL5eJOSdxUhxljhnWKEqQ7jYm9obRzqtIqorYeIMGtePe2lxVH/6dGvX9P+OxxdN0M6Gf6s2ssp/oAi5Tx/BKgb/iWFz505e1JIk/BY5cfDJyegDy7gLd6A7BeI+no36pBsVfX9IXtOs3xjLHNAU/MNHU=
  bucket: nickysemenza.com
  local-dir: public
  skip_cleanup: true
  acl: public-read
  on:
    branch: master
    repo: nickysemenza/nickysemenza.com
